branches:
  only:
  - master
  - develop
  - devops_branch
matrix:
  include:
    # Linux GCC
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - jonathonf/gcc-9.0
          packages:
            - cmake-data
            - cmake
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

jobs:
  include:
    - stage: build
      script:
        - eval "${MATRIX_EVAL}"
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
    - stage: test
      script: ./output/bin/tests/red_engine_test -r xml -d yes --order lex
