language: cpp
branches:
  only:
  - master
  - develop
  - devops_branch
matrix:
  include:
    # Linux GCC
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Linux Clang
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - cmake --build .