version: 1.0.{build}
branches:
  only:
  - master
  - develop
skip_tags: true
clone_script:
- git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- git checkout -qf %APPVEYOR_REPO_COMMIT%
image:
- Visual Studio 2019
- Ubuntu
build_script:
- >-
    mkdir build
    cd build

    cmake ..

    cmake --build . --config "Debug"

test_script:
- %APPVEYOR_BUILD_FOLDER%/output/test/red_engine_test
deploy: off