name: CI Workflow

on:
  push:
    branches:
      - master
      - develop
      - devops_branch
  pull_request:
    branches:
      - master
      - develop
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [linux64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependancies
      run:  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt update && sudo apt install libsdl2-dev g++-11
    - name: Build
      run: cd scripts && chmod a+x GenerateMakeProject.sh && chmod a+x bin/premake5 && ./GenerateMakeProject.sh && make -C projects/linux_gmake2 -j8 config=${{ matrix.config }}_${{ matrix.platform }} CC=gcc-11 CXX=g++-11 
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [Win64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,]'
    - name: Build
      run: |
        cd scripts
        call GenerateVs2022Project.bat
        msbuild projects/windows_vs2022/RedEngine.sln /t:Build /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }}
      shell: cmd