name: CI Workflow

on:
  push:
    branches:
      - master
      - develop
      - devops_branch
  pull_request:
    branches:
      - master
      - develop
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [Win64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cd scripts && ./GenerateProject.sh
    - name: Test
      run: scripts/bin/premake5 test --test-all
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [Win64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: |
        cd scripts
        call GenerateProject.bat
        msbuild projects/vs2019/RedEngine.sln /t:Build /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }}
      shell: cmd
    # - name: Test
    #   run: scripts/bin/premake5.exe test --test-all
    #   shell: cmd